blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    # url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.db.models import DateTimeField
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Roboczy'),
                      ('published', 'Opublikowany'))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               related_name='blog_posts',
                               on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    object = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug
                             ]
                       )

    class Meta:
        ordering = ('-publish', 'author')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return 'Komentarz dodany przez {} do {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post, Comment
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    template_name = 'blog/post/list.html'
    posts_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(posts_list, 1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'page': page,
               'posts': posts}
    return render(request, template_name, context)


def post_detail(request, year, month, day, post):
    template_name = 'blog/post/detail.html'
    # context = {'post': post, }
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day
                             )
    # List of active comments for this posta
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # A comments was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but dont save to database
            new_comment = comment_form.save(commit=False)
            # Assign the current post to comment
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {'post': post,
               'comments': comments,
               'comment_form': comment_form}

    return render(request, template_name, context)
    # return render(request, template_name, context)


def post_share(request, post_id):
    # Pobranie posta na podstawie jego identyfikatora
    template_name = 'blog/post/share.html'
    post = get_object_or_404(Post, id=post_id, status='published')
    # post = Post.object.get(id=post_id)
    sent = False

    if request.method == 'POST':
        email_form = EmailPostForm(request.POST)
        if email_form.is_valid():
            cd = email_form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) zachęca do przeczytania "{}"'.format(
                cd['name'], cd['email'], post.title)
            massage = 'Przeczytaj post "{}" na stronie {} \n\n Komentarz dodany\
                       przez {}: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, massage, 'admin@blog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    context = {'post': post,
               'form': form,
               'sent': sent}
    return render(request, template_name, context)

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>Mój pierwszy blog</h2>
                <p>To jest mój blog.</p>
        </div>
    </body>
</html>

blog/templates/blog/list/list.html
{% extends "blog/base.html" %}
{% block title %}
    Mój pierwszy blog
{% endblock %}

{% block content %}
    <h1>Mój blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>

        <p class="date">
            Opublikowany {{ post.publish }} przez {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date"> Opublikowany {{ post.publish }} przez {{ post.author }}</p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Udostępnij post</a>
    </p>
    {% with comments.count as total_comments %}
        {{ total_comments }} komentarz{{ total_comments|pluralize }}
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Komentarz {{ foorloop.counter }} opublikowany przez {{ comment.name }}, {{ comment.created }}
            </p>
                {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Jeszcze brak komentarzy</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Komentarz został dodany</h2>
    {% else %}
        <h2>Dodaj nowy komentarz </h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Dodaj komentarz">
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}
    Mój pierwszy blog
{% endblock %}

{% block content %}
    <h1>Mój blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>

        <p class="date">
            Opublikowany {{ post.publish }} przez {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
        {% if tag %}
            <h2>Tagi "{{ tag.name }}"</h2>
        {% endif %}
    {% endfor %}
    <!--{% include "blog/post/pagination.html" with page=page_obj %}-->
    {% include "blog/post/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-left">
        {% if  page.has_previous%}
            <a href="?page=1">&laquo; Pierwsza</a>
            <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Następna</a>
            <a href="?page={{ page.paginator.num_pages }}">Ostania &raquo;</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    Udostępnij post
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Wiadomość e-mail została wysłana</h1>
        <p>
            Wysłanie posta "{{ post.titlle }}" do !{{ cd.to }}! zakończyłą się sukcesem.
        </p>
    {% else %}
        <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Wyślij wiadomość e-mail">
        </form>
    {% endif %}
{% endblock %}